### ISSUE TITLE
Map change drops current items when len is two

### ISSUE THREAD

**Issue by jcdeargaez** [cognitedata/Expression#109]
When adding a new item to a `Map` having 2 items, using change method adds the new item but drops the items it had.

```python
Map.empty().change(1, lambda _: Some(1)).change(2, lambda _: Some(2)).change(3, lambda _: Some(3))
```

A Map having 3 items is expected, but actually the resulting Map only has (3, 3).

<img width="823" alt="image" src="https://user-images.githubusercontent.com/14651428/215131672-0e875fc8-85be-4e01-b4d4-aca5022869ad.png">

 - OS [MacOS]
 - Expression version [4.2.2]
 - Python version [3.11.1]

**Comment by dbrattli** [comment]
Thanks for opening this issue. This is indeed a bug and there's a few return statements missing in the code. This will be fixed in the next release.
