### ISSUE TITLE
Try docs

### ISSUE THREAD

**Issue by bgrounds** [cognitedata/Expression#45]
Not sure if this is intentional, but the docs for the Try class are nearly identical to the docs for the Result class.

I would expect the source code reference for Try to show a type alias (`Try = Result[TSource, Exception]`) or sub-class definition.

https://cognitedata.github.io/Expression/expression/

**Comment by dbrattli** [comment]
Yes, the pdoc3 generator is not handling type aliases that well. We should consider moving the docs to sphinx.

**Comment by dbrattli** [comment]
This issue should now be fixed after moving docs to Jupyter Book and ReadTheDocs: https://expression.readthedocs.io/en/latest/reference/try.html
