### ISSUE TITLE
 PEP634 - Structural Pattern Matching Suport?

### ISSUE THREAD

**Issue by lucasteles** [cognitedata/Expression#83]
Will we have support for `Option` and `Result` with [PEP634](https://peps.python.org/pep-0634/) ?

**Comment by dbrattli** [comment]
I think for most part it should work, but I'm not sure you will be able to unwrap the option/result to get the inner value. But please try to make some examples and submit as a PR. PEP634 is not a matching protocol which would have made it easier for us (if it had been).

**Comment by dbrattli** [comment]
This will be fixed in the next release

**Comment by dbrattli** [comment]
@lucasteles Thanks for asking about this. I decided to remove the legacy custom pattern matching in favor of python 3.10. Expression should be lot better because of this. I'm upgrading all projects to use Python 3.10 because of this.
